[metadata]
name = cooperative_gcs
version = 0.0.1
description = Cooperative GCS ROS2 Python package
author = maintainer

[options]
packages = find:
package_dir =
    = src
install_requires =
    setuptools
    rclpy
    std_msgs
    matplotlib
    pyyaml
    pandas
    numpy
zip_safe = false
include_package_data = true

[options.packages.find]
where = src

[options.package_data]
trajectory_data =
    *.csv
utilities =
    *.yaml

[develop]
script_dir=$base/lib/cooperative_gcs

[install]
install_scripts=$base/lib/cooperative_gcs

[options.data_files]
share/ament_index/resource_index/packages =
    resource/cooperative_gcs
share/cooperative_gcs =
    package.xml
share/cooperative_gcs/launch =
    launch/User_Interface.launch.py

[options.entry_points]
console_scripts =
    User_Interface = data_n_hmi.User_Interface:main
