[metadata]
name = cooperative_gcs
version = 0.0.1
description = Cooperative GCS ROS2 Python package
author = maintainer

[options]
packages = find:
install_requires =
    setuptools
    rclpy
    std_msgs
    matplotlib
    pyyaml
    pandas
    numpy
zip_safe = false
include_package_data = true

[options.packages.find]
where = .

[options.package_data]
cooperative_gcs.trajectory_data =
    *.csv
cooperative_gcs.utilities =
    *.yaml

[develop]
script_dir=$base/lib/cooperative_gcs

[install]
install_scripts=$base/lib/cooperative_gcs

[options.data_files]
share/ament_index/resource_index/packages =
    resource/cooperative_gcs
share/cooperative_gcs =
    package.xml
share/cooperative_gcs/launch =
    launch/User_Interface.launch.py
share/cooperative_gcs/trajectory_data =
    cooperative_gcs/trajectory_data/10_31_CAR_Gate_to_Charging_Station.csv
    cooperative_gcs/trajectory_data/12_09_buckeyelot_striaght.csv
    cooperative_gcs/trajectory_data/rotated_trajectory_45.0.csv
    cooperative_gcs/trajectory_data/rotated_trajectory_90.0.csv
    cooperative_gcs/trajectory_data/trajectory data/12_09_buckeyelot_striaght.csv

[options.entry_points]
console_scripts =
    User_Interface = cooperative_gcs.data_n_hmi.User_Interface:main
