[metadata]
name = noised_sensors
version = 0.0.1
description = Noised Sensors ROS2 Python package
author = Your Name

[options]
packages = find:
install_requires =
    setuptools
    rclpy
    std_msgs
zip_safe = false
include_package_data = true

[options.packages.find]
where = .

[options.data_files]
share/ament_index/resource_index/packages =
    resource/noised_sensors
share/noised_sensors =
    package.xml
    launch/sensor_wb_node.launch.py

[options.entry_points]
console_scripts =
    sensor_wb_node = noised_sensors.sensor_wb_node:main

[install]
install_scripts=$base/lib/noised_sensors
