[metadata]
name = safety_controller
version = 0.0.1
description = Safety Controller ROS2 Python package
author = maintainer

[options]
packages = find:
install_requires =
    setuptools
    rclpy
    std_msgs
    matplotlib
    pyyaml
    pandas
    numpy
    POT
zip_safe = false
include_package_data = true

[options.packages.find]
where = .

[options.package_data]
trajectory_data =
    *.csv
utilities =
    *.yaml

[develop]
script_dir=$base/lib/safety_controller

[install]
install_scripts=$base/lib/safety_controller

[options.data_files]
share/ament_index/resource_index/packages =
    resource/safety_controller
share/safety_controller =
    package.xml
share/safety_controller/launch =
    launch/simulation.launch.py
share/safety_controller/utilities =
    safety_controller/utilities/config.yaml
    safety_controller/utilities/config_IFAC.yaml
share/safety_controller/trajectory data =
    safety_controller/trajectory data/10_31_CAR_Gate_to_Charging_Station.csv
    safety_controller/trajectory data/10_31_CAR_parking_lot_rect_test_facing_north.csv
    safety_controller/trajectory data/10_31_CAR_parking_lot_rect_test_facing_west.csv
    safety_controller/trajectory data/11_14_CAR_test_from_charging_station_to_gate.csv
    safety_controller/trajectory data/11_14_CAR_west_short.csv
    safety_controller/trajectory data/11_14_West_Campus_Lane_Ave_long_right_man.csv
    safety_controller/trajectory data/11_14_West_campus_lane_ave_short_left_turn.csv
    safety_controller/trajectory data/11_24_West_Campus_SCurve.csv
    safety_controller/trajectory data/11_25_buckeyelot_Scurve.csv
    safety_controller/trajectory data/11_28_Carmac_S_Curve.csv
    safety_controller/trajectory data/12_01_Carmac_Scurve_busstop.csv
    safety_controller/trajectory data/12_03_buckeyelot_Scurve.csv
    safety_controller/trajectory data/12_07_buckeyelot_large_S.csv
    safety_controller/trajectory data/12_09_buckeyelot_striaght.csv
    safety_controller/trajectory data/1124_Scurve_new.csv
    safety_controller/trajectory data/01_17_Buckeyelot_straight.csv
    safety_controller/trajectory data/CAR FRONT 28 Jan STRAIGHT (chrg to -).csv
    safety_controller/trajectory data/CAR_longrun.csv
    safety_controller/trajectory data/CAR_rndabt_uturn.csv
    safety_controller/trajectory data/CAR_test_Buckeyelot_straight_10_30.csv
    safety_controller/trajectory data/Oct31_front_parking_lot_7mph_2.csv

[options.entry_points]
console_scripts =
    simulation = safety_controller.simulation:main
