[metadata]
name = common
version = 0.0.1
description = Common ROS2 Python package
author = maintainer

[options]
packages = find:
install_requires =
    setuptools
    rclpy
    std_msgs
    matplotlib
    pyyaml
    pandas
    numpy
    POT
zip_safe = false
include_package_data = true

[options.packages.find]
where = .

[options.package_data]
trajectory_data =
    *.csv
utilities =
    *.yaml

[develop]
script_dir=$base/lib/common

[install]
install_scripts=$base/lib/common

[options.data_files]
share/ament_index/resource_index/packages =
    resource/common
share/common =
    package.xml
share/common/utilities =
    common/utilities/config.yaml
    common/utilities/config_IFAC.yaml
share/common/trajectory_data =
    common/trajectory_data/10_31_CAR_Gate_to_Charging_Station.csv
    common/trajectory_data/10_31_CAR_parking_lot_rect_test_facing_north.csv
    common/trajectory_data/10_31_CAR_parking_lot_rect_test_facing_west.csv
    common/trajectory_data/11_14_CAR_test_from_charging_station_to_gate.csv
    common/trajectory_data/11_14_CAR_west_short.csv
    common/trajectory_data/11_14_West_Campus_Lane_Ave_long_right_man.csv
    common/trajectory_data/11_14_West_campus_lane_ave_short_left_turn.csv
    common/trajectory_data/11_24_West_Campus_SCurve.csv
    common/trajectory_data/11_25_buckeyelot_Scurve.csv
    common/trajectory_data/11_28_Carmac_S_Curve.csv
    common/trajectory_data/12_01_Carmac_Scurve_busstop.csv
    common/trajectory_data/12_03_buckeyelot_Scurve.csv
    common/trajectory_data/12_07_buckeyelot_large_S.csv
    common/trajectory_data/12_09_buckeyelot_striaght.csv
    common/trajectory_data/1124_Scurve_new.csv
    common/trajectory_data/01_17_Buckeyelot_straight.csv
    common/trajectory_data/CAR FRONT 28 Jan STRAIGHT (chrg to -).csv
    common/trajectory_data/CAR_longrun.csv
    common/trajectory_data/CAR_rndabt_uturn.csv
    common/trajectory_data/CAR_test_Buckeyelot_straight_10_30.csv
    common/trajectory_data/Oct31_front_parking_lot_7mph_2.csv
